source: src
default_build: release
update_source: nosial/libs.opts@n64
repository:
  name: n64
  type: github
  host: git.n64.cc
  ssl: true
assembly:
  name: OptsLib
  package: net.nosial.optslib
  version: 1.1.4
  description: 'A simple options parser library for PHP'
  copyright: 'Copyright (c) 2022-2026 Nosial'
build_configurations:
  -
    name: release
    output: 'target/release/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
  -
    name: debug
    output: 'target/debug/${ASSEMBLY.PACKAGE}.ncc'
    type: ncc
    definitions:
      DEBUG: '1'
